=== marschmidt/PdfReport/ewave-unimedsa/target/classes/xsd/customer-readjustment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.unimedsa.com.br/customer/readjustment" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.unimedsa.com.br/customer/readjustment">

    <complexType name="readjustment">
    	<sequence>
			<element name="contact" type="tns:contact"></element>
    		<element name="customer" type="tns:customer"></element>
    		<element name="value" type="string"></element>
    		<element name="date" type="date"></element>
    		<element name="printingDate" type="date"></element>
    	</sequence>
    </complexType>

    <complexType name="customer">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="streetName" type="string"></element>
    		<element name="streetNumber" type="string"></element>
    		<element name="neighborhood" type="string"></element>
    		<element name="city" type="string"></element>
    		<element name="cep" type="string"></element>
    	</sequence>
    </complexType>
    
    <complexType name="contact">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="phone" type="string"></element>
    		<element name="email" type="string"></element>
    	</sequence>
    </complexType>

    <element name="readjustments" type="tns:readjustments"></element>

    <complexType name="readjustments">
    	<sequence>
    		<element name="readjustment" type="tns:readjustment" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
</schema>

=== marschmidt/PdfReport/ewave-unimedsa/target/classes/xsd/customer-readjustment.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:readjustments xmlns:tns="http://www.unimedsa.com.br/customer/readjustment"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.unimedsa.com.br/customer/readjustment customer-readjustment.xsd ">
	<tns:readjustment>
		<tns:contact>
			<tns:name>Adriana</tns:name>
			<tns:phone>3471-3027</tns:phone>
			<tns:email>adriana.martins@unimedsa.com.br</tns:email>
		</tns:contact>
		<tns:customer>
			<tns:name>João Amaral</tns:name>
			<tns:streetName>Avenida Paulista</tns:streetName>
			<tns:streetNumber>340</tns:streetNumber>
			<tns:neighborhood>Centro</tns:neighborhood>
			<tns:city>São Paulo</tns:city>
			<tns:cep>44000-850</tns:cep>
		</tns:customer>
		<tns:value>1,4%</tns:value>
		<tns:date>2001-03-01</tns:date>
		<tns:printingDate>2001-02-01</tns:printingDate>
	</tns:readjustment>
	<tns:readjustment>
		<tns:contact>
			<tns:name>Adriana</tns:name>
			<tns:phone>3471-3027</tns:phone>
			<tns:email>adriana.martins@unimedsa.com.br</tns:email>
		</tns:contact>
		<tns:customer>
			<tns:name>Antônio da Silva</tns:name>
			<tns:streetName>Avenida Marechal Deodoro</tns:streetName>
			<tns:streetNumber>1233</tns:streetNumber>
			<tns:neighborhood>Cristo Rei</tns:neighborhood>
			<tns:city>Curitiba</tns:city>
			<tns:cep>88000-850</tns:cep>
		</tns:customer>
		<tns:value>3%</tns:value>
		<tns:date>2012-11-20</tns:date>
		<tns:printingDate>2001-10-01</tns:printingDate>
	</tns:readjustment>
	<tns:readjustment>
		<tns:contact>
			<tns:name>Adriana</tns:name>
			<tns:phone>3471-3027</tns:phone>
			<tns:email>adriana.martins@unimedsa.com.br</tns:email>
		</tns:contact>
		<tns:customer>
			<tns:name>José Almeida Silva</tns:name>
			<tns:streetName>Avenida 23 de Maio</tns:streetName>
			<tns:streetNumber>584</tns:streetNumber>
			<tns:neighborhood>Chácara Flora</tns:neighborhood>
			<tns:city>São Paulo</tns:city>
			<tns:cep>48022-450</tns:cep>
		</tns:customer>
		<tns:value>2,8%</tns:value>
		<tns:date>2012-11-15</tns:date>
		<tns:printingDate>2001-10-15</tns:printingDate>
	</tns:readjustment>
	<tns:readjustment>
		<tns:contact>
			<tns:name>Adriana</tns:name>
			<tns:phone>3471-3027</tns:phone>
			<tns:email>adriana.martins@unimedsa.com.br</tns:email>
		</tns:contact>
		<tns:customer>
			<tns:name>Luiz Nicodemo</tns:name>
			<tns:streetName>Avenida 23 de Maio</tns:streetName>
			<tns:streetNumber>584</tns:streetNumber>
			<tns:neighborhood>Chácara Flora</tns:neighborhood>
			<tns:city>São Paulo</tns:city>
			<tns:cep>48022-450</tns:cep>
		</tns:customer>
		<tns:value>2,8%</tns:value>
		<tns:date>2012-08-07</tns:date>
		<tns:printingDate>2001-07-07</tns:printingDate>
	</tns:readjustment>	
</tns:readjustments>
